### ISSUE TITLE
ValueError: noverlap must be less than nperseg

### ISSUE THREAD

**Issue by fzlittlekid** [hche11/Localizing-Visual-Sounds-the-Hard-Way#15]
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/difffoley/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/difffoley/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/difffoley/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-fs/hfz/Localizing-Visual-Sounds-the-Hard-Way/datasets/dataloader.py", line 91, in __getitem__
    frequencies, times, spectrogram = signal.spectrogram(resamples,samplerate, nperseg=512,noverlap=274)
  File "/root/miniconda3/envs/difffoley/lib/python3.8/site-packages/scipy/signal/_spectral_py.py", line 763, in spectrogram
    freqs, time, Sxx = _spectral_helper(x, x, fs, window, nperseg,
  File "/root/miniconda3/envs/difffoley/lib/python3.8/site-packages/scipy/signal/_spectral_py.py", line 1809, in _spectral_helper
    raise ValueError('noverlap must be less than nperseg.')
ValueError: noverlap must be less than nperseg.

but nperseg=512, noverlap=274

...python3.8/site-packages/scipy/signal/_spectral_py.py:2014: UserWarning: nperseg = 512 is greater than input length  = 2, using nperseg = 2
in detail, after
       window, nperseg = _triage_segments(window, nperseg, input_length=x.shape[axis])
nperseg change to 2

**Comment by fzlittlekid** [comment]
Because the input is stereo audio, the shape is (441000, 2), which causes the subsequent operation to modify nperseg
